<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfxjFJf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfxjFJf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfxjFJf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfxjFJf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXfxjFJf\App_KernelDevDebugContainer([
    'container.build_hash' => 'XfxjFJf',
    'container.build_id' => 'd62813a3',
    'container.build_time' => 1630680453,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfxjFJf');
